-- List top 3 restaurants by highest average order value.
select
    *,
    count(restaurantsid)
from
    orders
    join restaurants on orders.restaurantsid = restaurants.id
group by
    restaurantsid;

-- Find all users who placed more than 5 completed orders in the last 30 days.
select
    c.name Name,
    count(c.id) TotalOrders
from
    orders o
    join customers c on o.customerid = c.id
where
    o.orderstatus = 'success'
group by
    c.id
having
    count(c.id) > 5;

-- Get the total revenue generated by each restaurant in the last month.
SELECT
    res.id,
    res.name,
    SUM(m.price * o.quantity) TotalRevenue
FROM
    orders o
    JOIN menu m ON o.menuid = m.id
    JOIN restaurants res ON o.restaurantsid = res.id
WHERE
    orderstatus = 'success'
    AND orderdate >= DATE_SUB (CURDATE (), INTERVAL 1 MONTH)
GROUP BY
    res.name
ORDER BY
    res.id;

-- Find the most popular menu item (ordered most times across all restaurants).
select
    m.name,
    count(menuid) orderTimes
from
    orders o
    join menu m on o.menuid = m.id
group by
    m.id
order by
    orderTimes desc
limit
    1;

-- Find the users who have never placed an order.
select
    c.id,
    c.name
from
    orders o
    right join customers c on o.customerid = c.id
where
    o.id is null
order by
    c.id;

-- For each restaurant, show the most ordered item and its total quantity.
SELECT
    Restaurant,
    MenuItems,
    totalQuantity
FROM
    (
        SELECT
            r.name Restaurant,
            m.name MenuItems,
            SUM(o.quantity) AS totalQuantity,
            row_number() over (
                partition by
                    r.id
                order by
                    sum(o.quantity) desc
            ) rest_no
        FROM
            orders o
            JOIN menu m ON o.menuid = m.id
            JOIN restaurants r ON o.restaurantsid = r.id
        GROUP BY
            r.id,
            m.id
        ORDER BY
            r.name,
            totalQuantity DESC
    ) t
where
    rest_no = 1;